epoch: 30
batch_size: 24
lr: 0.0001
worker: 4

image_size: 256

source_folder: /archive/datasets/tseng_inpaint_strategy/celebA_iccv/celebA_inputs/randpolys/
target_folder: /archive/datasets/tseng_inpaint_strategy/celebA_iccv/celebA_label/randpolys/
